# Copyright 2025 OppositeNor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from typing import Any
from jinja2 import Environment, FileSystemLoader, select_autoescape
from build_script.utils import hash_file, hash_str_sha256
from build_script.reflection.gen_file_info import WBEGenFileInfo
from build_script.reflection.parameter_resolver import (
    WBEParameterSource,
    WBEEnvParameterSource,
    WBEParameterResolver,
)
import build_setup
from pydantic import BaseModel, Field

GENERATE_PREFIX = "This file is generated by the White Bird Engine code generator. Direct modification to this file should be avoided."

class WBECodeGenerator:
    """The code generator."""
    def __init__(self, attributes: dict[str, Any], generate_infos: list[WBEGenFileInfo],
                 extra_sources: list[WBEParameterSource] | None = None) -> None:
        """Constructor.

        Args:
            attributes: The attributes to replace the data starting with '.'.
            generate_infos: The generation infos.
            extra_sources: Optional list of WBEParameterSource instances injected
                           at build level. Queried after per-entry params but before
                           environment variables.
        """
        self._attributes = attributes
        # Build the base resolver: extra_sources first, then env vars as fallback.
        base_sources: list[WBEParameterSource] = list(extra_sources) if extra_sources else []
        base_sources.append(WBEEnvParameterSource())
        self._base_resolver = WBEParameterResolver(base_sources)
        # Create a template environment in the root_dir
        self._env = Environment(
            loader=FileSystemLoader(build_setup.template_dir),
            autoescape=select_autoescape(),
            trim_blocks=True,
            lstrip_blocks=True
        )
        self._generate_infos = generate_infos

    def generate(self) -> None:
        """Generate."""
        for generate_info in self._generate_infos:
            self._generate(generate_info)

    def _generate(self, generate_info: WBEGenFileInfo) -> None:
        resolved = self._base_resolver.resolve_gen_file_info(generate_info)

        data: dict[str, Any] = resolved.data
        for key, value in data.items():
            # If it starts with a '.', get the data from attributes.
            if isinstance(value, str) and value[0] == '.':
                data[key] = self._attributes[key]
            if key[0] == '_':
                raise RuntimeError(f"Failed to generate file: {resolved.output_name}. " +
                    f"Data: {key} starts with an underscore, which is preserved by the generator.")

        template = self._env.get_template(resolved.template)
        data["_prefix"] = GENERATE_PREFIX
        output = template.render(data)

        output_path = os.path.join(resolved.out_dir, resolved.output_name)
        os.makedirs(resolved.out_dir, exist_ok=True)
        if not os.path.exists(output_path) or hash_file(output_path) != hash_str_sha256(output):
            # Only export when found different from what was generated to not trigger
            # the CMake compilation.
            with open(output_path, "w") as f:
                f.write(output)


