# Copyright 2025 OppositeNor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape
from build_setup import template_dir, template_output_dir

GENERATE_PREFIX = "/* This file is generated by the White Bird Engine code generator.*/\n"

class WBECodeGenerator:
    """White Bird Engine code generator.

    Attributes: 
        metadata: The metadata.
        env: The jinja environment.
    """
    def __init__(self, metadata):
        """Constructor.

        Args:
            metadata (): The metadata.
        """
        self.metadata = metadata
        # Create a template environment in the root_dir
        self.env = Environment(
            loader=FileSystemLoader(template_dir),
            autoescape=select_autoescape()
        )

    def generate(self):
        """Generate."""
        template_dir_path = Path(template_dir)
        for template_file in template_dir_path.iterdir():
            template = self.env.get_template(str(template_file.name))
            output = template.render(self.metadata)
            output = GENERATE_PREFIX + output
            with open(os.path.join(template_output_dir, template_file.stem), "w") as f:
                f.write(output)


